### ISSUE TITLE
Books once added cannot be deleted

### ISSUE THREAD

**Issue by agzuniverse** [agzuniverse/MecBooksWatch#47]
Add an option to delete book, preferably by a button on the book's card.
* Only the user who uploaded the book should be able to delete the book. (So the delete book button should come up only in the books shown in Userpage)
* There should be some sort of confirmation popup on clicking the button.
* When a book is deleted the not only should the entry be removed from firestore, the corresponding image should be removed from firebase storage.

**Comment by 123vivekr** [comment]
@agzuniverse Please change UI to accommodate book delete feature.

**Comment by agzuniverse** [comment]
UI completed, fix errors in the delete function @123vivekr . Once you have tested and verified your function can successfully delete books, close the issue.
